# Generated by Django 4.0.6 on 2022-07-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leetcode_username',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
